/* ════════════════════════════════════════════════════════════════════════
   VOICE AGENT: call scripts. Each call is a deterministic replay of a
   production voice-agent pipeline (STT → LLM + tools → TTS): agent and
   caller turns, tool calls mid-conversation, and one visitor-triggered
   barge-in the agent recovers from. Agent lines marked `interruptible`
   arm the interrupt button; `barge.events` is the full alternate tail.
   ════════════════════════════════════════════════════════════════════════ */

export const CALLS = [
  {
    id: 'clinic',
    icon: '🦷',
    domain: 'Healthcare · Front desk',
    direction: 'Inbound call',
    persona: 'Maya, front-desk voice agent at Nova Dental',
    short: 'Clinic',
    goal: 'Hi, I need a cleaning this week, ideally in the evening.',
    bargeLabel: 'Change your plans',
    bargeHint: 'Wait for the agent to offer slots, then cut in.',
    events: [
      { t: 'agent', text: 'Nova Dental, this is Maya. How can I help you today?' },
      { t: 'caller', text: 'Hi, I need a cleaning this week, ideally in the evening.' },
      { t: 'think', text: 'Intent: cleaning · window: this week, evenings. Verify identity, then check the diary.' },
      { t: 'agent', text: 'Of course. Can I get your name and date of birth to pull up your file?' },
      { t: 'caller', text: 'Priya Nair, March 14th, ninety-two.' },
      { t: 'tool', call: "patients.lookup(name: 'Priya Nair', dob: '1992-03-14')", ms: 1000, result: 'file found · last visit 8 months ago' },
      { t: 'tool', call: "calendar.slots(service: 'cleaning', window: 'this week · evenings')", ms: 1200, result: '2 slots open',
        art: { kind: 'kv', rows: [['Tue', '17:30 · Dr. Rao'], ['Thu', '18:15 · Dr. Rao']] } },
      { t: 'agent', text: 'I have Tuesday at five-thirty, or Thursday at six-fifteen with Dr. Rao. Which works better for you?', interruptible: true },
      { t: 'caller', text: "Thursday at 6:15. Oh, and is the cleaning fully covered on my insurance?" },
      { t: 'tool', call: "kb.search('Star Health · preventive cleaning cover')", ms: 1100, result: 'covered 100% · visit 2 of 2 this year' },
      { t: 'agent', text: "Yes, cleanings are fully covered on your plan, and this would be your second free visit this year." },
      { t: 'tool', call: "calendar.book(patient: 'P. Nair', slot: 'Thu 18:15')", ms: 1100, result: 'confirmed · #APT-2214' },
      { t: 'tool', call: "sms.send(confirmation + reminder: 'T-24h')", ms: 800, result: 'sent',
        art: { kind: 'msg', title: 'SMS · sent during the call', body: 'Nova Dental: you’re booked for a cleaning on Thu 6:15 pm with Dr. Rao. Fully covered by Star Health. Reply R to reschedule.' } },
      { t: 'agent', text: "You're booked for Thursday at six-fifteen. The confirmation is on your phone. See you then, Priya." },
      { t: 'caller', text: 'Perfect, thanks!' },
      { t: 'done' },
    ],
    barge: {
      events: [
        { t: 'caller', text: 'Oh wait, sorry, my shift changed and evenings are out. Anything Saturday morning?' },
        { t: 'think', text: 'Constraint flipped mid-offer. Drop the evening holds, re-query Saturday morning.' },
        { t: 'tool', call: "calendar.slots(window: 'Sat · 09:00–12:00')", ms: 1100, result: 'Sat 09:40 · 11:20 open' },
        { t: 'agent', text: 'No problem at all. Saturday I have nine-forty or eleven-twenty. Which do you prefer?' },
        { t: 'caller', text: "9:40. And is the cleaning fully covered on my insurance?" },
        { t: 'tool', call: "kb.search('Star Health · preventive cleaning cover')", ms: 1000, result: 'covered 100% · visit 2 of 2 this year' },
        { t: 'agent', text: 'Fully covered. This would be your second free visit this year.' },
        { t: 'tool', call: "calendar.book(patient: 'P. Nair', slot: 'Sat 09:40')", ms: 1100, result: 'confirmed · #APT-2219' },
        { t: 'tool', call: "sms.send(confirmation + reminder: 'T-24h')", ms: 800, result: 'sent',
          art: { kind: 'msg', title: 'SMS · sent during the call', body: 'Nova Dental: you’re booked for a cleaning on Sat 9:40 am with Dr. Rao. Fully covered by Star Health. Reply R to reschedule.' } },
        { t: 'agent', text: "You're booked for Saturday at nine-forty. The confirmation is on your phone. See you then, Priya." },
        { t: 'caller', text: 'Perfect, thanks!' },
        { t: 'done' },
      ],
      outcome: {
        headline: 'Interrupted mid-offer. Rebooked without missing a beat.',
        detail: 'The caller changed the constraint while the agent was speaking. It stopped, dropped its holds, re-queried the calendar and still closed the booking. That recovery is the hard part of voice AI.',
        extract: [
          ['intent', 'book · cleaning'],
          ['patient', 'Priya Nair · verified'],
          ['booked', 'Sat 09:40 · Dr. Rao'],
          ['insurance', 'covered · visit 2/2'],
          ['follow-up', 'SMS + reminder T-24h'],
        ],
        stats: [['5', 'tool calls'], ['1', 'barge-in handled'], ['0', 'hold music']],
      },
    },
    outcome: {
      headline: 'Booked, covered and confirmed in one call.',
      detail: 'Identity verified against the patient file, the diary checked, an insurance question answered from policy docs, the slot booked and the SMS sent. No hold music, no callback, no human in the loop.',
      extract: [
        ['intent', 'book · cleaning'],
        ['patient', 'Priya Nair · verified'],
        ['booked', 'Thu 18:15 · Dr. Rao'],
        ['insurance', 'covered · visit 2/2'],
        ['follow-up', 'SMS + reminder T-24h'],
      ],
      stats: [['4', 'tool calls'], ['1', 'appointment booked'], ['0', 'hold music']],
    },
  },

  {
    id: 'solar',
    icon: '☀️',
    domain: 'Solar · Outbound sales',
    direction: 'Outbound call',
    persona: 'Aria, sales voice agent at Suryan Solar',
    short: 'Solar sales',
    goal: 'Follow up on yesterday’s rooftop-solar quote request.',
    bargeLabel: 'Raise an objection',
    bargeHint: 'Wait for the agent’s pitch, then push back.',
    events: [
      { t: 'agent', text: 'Hi, is this Rahul? This is Aria from Suryan Solar. You asked for a quote on our site yesterday. Got two minutes?' },
      { t: 'caller', text: "Oh right, yeah, now's fine." },
      { t: 'think', text: 'Warm lead. Qualify: ownership, bill size, timeline. Then book the site survey.' },
      { t: 'agent', text: 'Great. Is the house your own, and roughly what’s the monthly power bill?' },
      { t: 'caller', text: 'Our own, two floors. Around four thousand a month, more in summer.' },
      { t: 'tool', call: "crm.update(lead: 'Rahul M.', property: 'owned · 2 floors', bill: '₹4k/mo')", ms: 900, result: 'lead updated' },
      { t: 'tool', call: "sizing.estimate(bill: '₹4,000/mo', region: 'Pune')", ms: 1300, result: 'system sized',
        art: { kind: 'kv', rows: [['system', '3 kW rooftop'], ['cost after subsidy', '₹1.9 L'], ['payback', '≈ 4 years', true]] } },
      { t: 'agent', text: 'That bill usually means a three-kilowatt system, about one point nine lakh after subsidy, and it pays for itself in four years. Should I book you a free roof survey?', interruptible: true },
      { t: 'caller', text: "Hmm, the subsidy's still on? I heard it's ending." },
      { t: 'tool', call: "kb.search('PM Surya Ghar subsidy · 3 kW · status')", ms: 1100, result: 'active · ₹78,000 · docs: Aadhaar + one bill' },
      { t: 'agent', text: 'Still active. Seventy-eight thousand off a three-kilowatt system, and we file the paperwork for you.' },
      { t: 'caller', text: "Okay, let's do the survey. Saturday, if you can." },
      { t: 'tool', call: "calendar.book(survey: 'Sat 10:00', engineer: 'field-2')", ms: 1100, result: 'booked · engineer assigned' },
      { t: 'tool', call: "crm.stage(lead → 'survey scheduled') · followup.email(checklist)", ms: 900, result: 'sent',
        art: { kind: 'msg', title: 'Email · sent during the call', body: 'Hi Rahul, your free roof survey is set for Saturday 10:00. Keep handy: one electricity bill and your Aadhaar for the ₹78k subsidy filing. Aria, Suryan Solar' } },
      { t: 'agent', text: 'Done. Saturday at ten. The checklist is in your inbox. Speak soon, Rahul.' },
      { t: 'done' },
    ],
    barge: {
      events: [
        { t: 'caller', text: 'Wait, my society has to approve rooftop work. Is that a problem?' },
        { t: 'think', text: 'Objection: housing-society approval. There’s a standard NOC letter. Answer it, then re-ask for the survey.' },
        { t: 'tool', call: "kb.search('housing society NOC · rooftop solar')", ms: 1100, result: 'template NOC · 40+ societies approved' },
        { t: 'agent', text: 'Usually not. Societies just need a no-objection letter, and we provide the standard template. Forty-plus societies nearby have signed it. Shall I still book that free survey?' },
        { t: 'caller', text: 'Alright, Saturday morning if you can.' },
        { t: 'tool', call: "calendar.book(survey: 'Sat 10:00', engineer: 'field-2')", ms: 1100, result: 'booked · engineer assigned' },
        { t: 'tool', call: "crm.stage(lead → 'survey scheduled') · followup.email(checklist + NOC template)", ms: 900, result: 'sent',
          art: { kind: 'msg', title: 'Email · sent during the call', body: 'Hi Rahul, survey set for Saturday 10:00. Attached: the society NOC template plus the subsidy checklist (one bill + Aadhaar). Aria, Suryan Solar' } },
        { t: 'agent', text: 'Done. Saturday at ten, and the NOC template is in your inbox with the checklist. Speak soon, Rahul.' },
        { t: 'caller', text: 'Thanks, bye.' },
        { t: 'done' },
      ],
      outcome: {
        headline: 'Objection raised mid-pitch. Answered, then closed.',
        detail: 'The caller cut the pitch off with a real blocker. The agent stopped talking, pulled the answer from its knowledge base, sent the NOC template, and still walked out with the meeting.',
        extract: [
          ['lead', 'Rahul M. · warm'],
          ['system', '3 kW · ₹1.9 L after subsidy'],
          ['objection', 'society NOC · resolved'],
          ['booked', 'site survey · Sat 10:00'],
          ['crm', 'stage: survey scheduled'],
        ],
        stats: [['5', 'tool calls'], ['1', 'objection handled'], ['1', 'meeting booked']],
      },
    },
    outcome: {
      headline: 'Qualified, answered and booked while the lead was warm.',
      detail: 'Ownership and bill captured to the CRM mid-sentence, the system sized on the call, a subsidy question answered from policy docs, and a survey on the calendar with the follow-up email already sent.',
      extract: [
        ['lead', 'Rahul M. · warm'],
        ['system', '3 kW · ₹1.9 L after subsidy'],
        ['objection', 'subsidy doubt · resolved'],
        ['booked', 'site survey · Sat 10:00'],
        ['crm', 'stage: survey scheduled'],
      ],
      stats: [['5', 'tool calls'], ['1', 'meeting booked'], ['<1 s', 'CRM lag']],
    },
  },
];
