/* ════════════════════════════════════════════════════════════════════════
   AGENT CONSOLE: mission scripts. Each mission is a deterministic replay:
   a plan, a stream of events (think / step / tool / alert), one optional
   visitor-triggered curveball the agent adapts to, and an outcome.
   Event `step` ids reference plan indices; curveball steps use c0, c1…
   ════════════════════════════════════════════════════════════════════════ */

export const MISSIONS = [
  {
    id: 'retail',
    icon: '🛒',
    domain: 'Retail · Analytics',
    short: 'Retail',
    goal: 'Checkout conversion dropped this week. Find out why.',
    plan: [
      'Pull the conversion funnel',
      'Segment the drop',
      'Correlate with releases',
      'Verify the root cause',
      'Draft the fix and report',
    ],
    events: [
      { t: 'think', text: 'A conversion drop is a funnel problem. First question: when did it start, and which step is bleeding?' },
      { t: 'step', id: 0 },
      { t: 'tool', call: "analytics.funnel(range: '14d')", ms: 1200, result: 'drop begins day 9 · 3.4% → 2.8%',
        art: { kind: 'spark', d: [3.4, 3.5, 3.3, 3.4, 3.6, 3.4, 3.5, 3.3, 3.4, 2.9, 2.8, 2.9, 2.8, 2.8], label: '2.8%', marker: 8, markerLabel: 'day 9' } },
      { t: 'think', text: 'A sharp knee, not a slow drift. Something changed on day 9.' },
      { t: 'step', id: 1 },
      { t: 'tool', call: "analytics.segment(step: 'payment', by: 'device')", ms: 1300, result: 'the drop is mobile-only',
        art: { kind: 'bars', rows: [
          { l: 'Desktop', v: 1.9, txt: '-1.9%' },
          { l: 'Tablet', v: 3.2, txt: '-3.2%' },
          { l: 'Mobile', v: 18, txt: '-18%', hot: true },
        ] } },
      { t: 'think', text: 'Mobile only, desktop flat. That rules out pricing, stock and payment outages.' },
      { t: 'step', id: 2 },
      { t: 'tool', call: "deploys.list(window: 'day 8-10')", ms: 1000, result: 'one release touches checkout',
        art: { kind: 'kv', rows: [
          ['v2.31 · day 9', 'checkout-ui', true],
          ['changeset', 'new address autocomplete'],
          ['v2.30 · day 8', 'email templates'],
        ] } },
      { t: 'step', id: 3 },
      { t: 'tool', call: "replay.sample(filter: 'mobile · abandoned at payment', n: 34)", ms: 1600, result: '34 sessions reviewed' },
      { t: 'alert', title: 'Root cause', text: 'The new autocomplete dropdown overlaps the Pay button on viewports under 380 px. Users tap, nothing happens, they leave.' },
      { t: 'step', id: 4 },
      { t: 'tool', call: "code.patch('checkout-ui/address.css')", ms: 1100, result: 'fix drafted · PR opened',
        art: { kind: 'diff', lines: ['  .autocomplete {', '-   z-index: 40;', '+   z-index: 10;', '+   max-height: 42vh;', '  }'] } },
      { t: 'tool', call: "report.draft(to: 'growth-team')", ms: 900, result: 'summary sent',
        art: { kind: 'msg', title: 'Report · drafted by the agent', body: 'Conversion drop isolated to mobile checkout: the v2.31 autocomplete overlays the Pay button under 380 px. One-line fix in review; est. recovery ≈ ₹4.2L/week.' } },
      { t: 'done' },
    ],
    curveball: {
      label: 'Traffic spike',
      steps: ['Hand the spike to on-call'],
      events: [
        { t: 'alert', title: 'Curveball', text: 'Marketing just launched a flash sale. Traffic is 6× normal, p95 latency 4.1 s and climbing.' },
        { t: 'step', id: 'c0' },
        { t: 'think', text: 'Tempting to chase, but the drop started on day 9 and this spike started minutes ago. Two different problems. Handing latency to on-call, staying on mission.' },
        { t: 'tool', call: "oncall.page(team: 'platform', severity: 'high')", ms: 900, result: 'acknowledged · autoscaling engaged' },
      ],
    },
    outcome: {
      headline: 'Root cause: a one-line CSS bug.',
      detail: 'Isolated to mobile in four steps, verified with session replays, fix PR opened and the report drafted, before anyone had to dig.',
      stats: [['6', 'tool calls'], ['1', 'root cause'], ['₹4.2L/wk', 'est. recovery']],
    },
  },

  {
    id: 'logistics',
    icon: '🚚',
    domain: 'Logistics · Operations',
    short: 'Logistics',
    goal: '480 kg of fragile machine parts, Mumbai → Delhi by Friday. Book the cheapest safe option.',
    plan: [
      'Compute chargeable weight',
      'Quote every mode',
      'Apply the constraints',
      'Book and schedule pickup',
      'Confirm to the customer',
    ],
    events: [
      { t: 'think', text: 'Freight is priced on chargeable weight, not actual. Dimensions first.' },
      { t: 'step', id: 0 },
      { t: 'tool', call: 'rates.chargeable(4 crates · 120×80×95 cm, 480 kg)', ms: 1000, result: 'volumetric beats actual',
        art: { kind: 'kv', rows: [['actual', '480 kg'], ['volumetric', '608 kg', true], ['chargeable', '608 kg', true]] } },
      { t: 'step', id: 1 },
      { t: 'tool', call: "quotes.fetch(modes: ['air', 'rail', 'FTL', 'LTL'])", ms: 1500, result: '4 quotes returned',
        art: { kind: 'bars', rows: [
          { l: 'Air', v: 58, txt: '₹58k · 1d', hot: true },
          { l: 'FTL', v: 22, txt: '₹22k · 2d' },
          { l: 'Rail', v: 19, txt: '₹19k · 4d' },
          { l: 'LTL', v: 15, txt: '₹15k · 5d' },
        ] } },
      { t: 'think', text: 'Rail and LTL miss Friday. Air makes it at 2.6× the cost. FTL lands Thursday at ₹22k. That is the answer, if fragile handling checks out.' },
      { t: 'step', id: 2 },
      { t: 'tool', call: "carriers.check(mode: 'FTL', cargo: 'fragile')", ms: 1100, result: 'carrier B qualifies',
        art: { kind: 'kv', rows: [['carrier B', 'air-ride suspension'], ['handling', 'strap kit included'], ['rating', '4.8 / 5']] } },
      { t: 'step', id: 3 },
      { t: 'tool', call: "booking.create(carrier: 'B', pickup: 'tomorrow 09:00')", ms: 1300, result: 'AWB #MH-2841 · pickup confirmed' },
      { t: 'step', id: 4 },
      { t: 'tool', call: "notify.customer(channel: 'email')", ms: 900, result: 'confirmation sent',
        art: { kind: 'msg', title: 'Customer email · drafted by the agent', body: 'Your shipment is booked: full-truck with air-ride suspension, pickup tomorrow 09:00, arriving Thursday. ₹22,400, 61% below air freight.' } },
      { t: 'done' },
    ],
    curveball: {
      label: 'Carrier cancels',
      steps: ['Rebook with the backup carrier'],
      events: [
        { t: 'alert', title: 'Curveball', text: 'Carrier B cancelled the 09:00 pickup. Truck breakdown.' },
        { t: 'step', id: 'c0' },
        { t: 'think', text: 'This is why you quote wide. Carrier C was ₹1.3k more with the same air-ride spec. Rebooking before the slot closes.' },
        { t: 'tool', call: "booking.rebook(carrier: 'C')", ms: 1200, result: 'AWB #MH-2857 · pickup 10:30 · ETA still Thursday' },
      ],
    },
    outcome: {
      headline: 'Booked: Thursday delivery at 39% of air freight.',
      detail: 'Chargeable weight computed, four modes quoted, constraints applied, carrier vetted for fragile cargo, booking and customer email done end to end.',
      stats: [['₹35.6k', 'saved vs air'], ['Thu', 'on-time ETA'], ['4.8★', 'carrier rating']],
    },
  },

  {
    id: 'energy',
    icon: '⚡',
    domain: 'Energy · EV Charging',
    short: 'Energy',
    goal: 'Five EVs plugged in tonight, one 14 kW fuse. Everything charged by morning at the lowest cost.',
    plan: [
      'Read the site',
      'Forecast price and load',
      'Solve the schedule',
      'Hold the battery for the peak',
      'Monitor overnight',
    ],
    events: [
      { t: 'think', text: 'Five cars at full power is 35 kW into a 14 kW fuse. This is a scheduling problem, not a power problem.' },
      { t: 'step', id: 0 },
      { t: 'tool', call: 'site.read()', ms: 1000, result: 'site state loaded',
        art: { kind: 'kv', rows: [['solar', '0 kW · night'], ['battery', '11.2 / 16 kWh'], ['building load', '3.8 kW'], ['fuse', '14 kW', true]] } },
      { t: 'step', id: 1 },
      { t: 'tool', call: "forecast.price(horizon: '12h')", ms: 1200, result: 'evening peak ₹12.4 at 19:00',
        art: { kind: 'spark', d: [8.2, 9.6, 11.8, 12.4, 11.9, 9.4, 6.1, 4.3, 3.8, 3.6, 3.9, 4.4], label: '₹/kWh', marker: 3, markerLabel: '19:00 peak', color: '#f5b942' } },
      { t: 'think', text: 'Two cars must leave by 07:00; the other three have slack. They charge after midnight at a third of the price.' },
      { t: 'step', id: 2 },
      { t: 'tool', call: 'schedule.solve(evs: 5, fuse: 14 kW)', ms: 1500, result: 'peak site draw 12.7 kW · 1.3 kW margin',
        art: { kind: 'bars', rows: [
          { l: 'EV-1', v: 7, txt: '7 kW · now' },
          { l: 'EV-2', v: 3.5, txt: '3.5 kW · now' },
          { l: 'EV-3', v: 11, txt: '11 kW · 00:30' },
          { l: 'EV-4', v: 11, txt: '11 kW · 02:00' },
          { l: 'EV-5', v: 7, txt: '7 kW · 04:00' },
        ] } },
      { t: 'step', id: 3 },
      { t: 'tool', call: "battery.dispatch(reserve: '19:00-21:00', kW: 4)", ms: 1000, result: 'battery carries the building through the peak' },
      { t: 'step', id: 4 },
      { t: 'tool', call: "watchdog.arm(rules: ['fuse', 'deadlines'])", ms: 900, result: 'monitoring · re-solves on any change' },
      { t: 'done' },
    ],
    curveball: {
      label: 'A sixth EV arrives',
      steps: ['Re-solve for the sixth car'],
      events: [
        { t: 'alert', title: 'Curveball', text: 'A sixth EV just plugged in at 21:40. It needs 22 kWh by 08:00.' },
        { t: 'step', id: 'c0' },
        { t: 'think', text: 'The solver re-runs in milliseconds. EV-4 has deadline slack. Shifting it 40 minutes frees a slot for the newcomer.' },
        { t: 'tool', call: 'schedule.resolve(evs: 6)', ms: 1100, result: 'still under the fuse · all deadlines met' },
      ],
    },
    outcome: {
      headline: 'All cars ready by 07:00. Fuse never touched.',
      detail: 'Deadline-aware charging shifted to cheap hours, the battery covered the price peak, and a watchdog re-solves the moment anything changes. This one is our day job at RiDERgy.',
      stats: [['-34%', 'energy cost'], ['0', 'fuse breaches'], ['5/5', 'cars ready']],
    },
  },

  {
    id: 'incident',
    icon: '🚨',
    domain: 'SaaS · Incident Response',
    short: 'Incident',
    goal: '3 a.m. page: API error rate climbing. Triage it before customers notice.',
    plan: [
      'Measure the blast radius',
      'Trace the failure',
      'Mitigate',
      'Verify recovery',
      'Write the incident note',
    ],
    events: [
      { t: 'step', id: 0 },
      { t: 'tool', call: "metrics.query(error_rate, by: 'endpoint')", ms: 1100, result: 'isolated to payment paths',
        art: { kind: 'bars', rows: [
          { l: '/payments', v: 14, txt: '14% err', hot: true },
          { l: '/checkout', v: 6, txt: '6% err', hot: true },
          { l: '/catalog', v: 0.2, txt: '0.2%' },
          { l: '/auth', v: 0.1, txt: '0.1%' },
        ] } },
      { t: 'step', id: 1 },
      { t: 'tool', call: "traces.sample(endpoint: '/payments', n: 50)", ms: 1300, result: '92% are upstream timeouts',
        art: { kind: 'kv', rows: [['p50', '180 ms'], ['p95', '30 000 ms · timeout', true], ['upstream', 'payproc-gw', true]] } },
      { t: 'think', text: 'Every slow trace dies at the same upstream. That smells like their outage, not our bug. Check their status before touching code.' },
      { t: 'tool', call: "status.check(vendor: 'payproc')", ms: 900, result: "vendor incident confirmed · 'degraded performance' since 02:41" },
      { t: 'step', id: 2 },
      { t: 'tool', call: "config.apply(fallback: 'razorpay', circuit_breaker: on)", ms: 1200, result: 'traffic failing over',
        art: { kind: 'diff', lines: ['  payments:', '-   provider: payproc', '+   provider: razorpay', '+   breaker: open @ 5xx > 2%'] } },
      { t: 'step', id: 3 },
      { t: 'tool', call: "metrics.watch(error_rate, '5m')", ms: 1600, result: 'recovered · 0.3% baseline',
        art: { kind: 'spark', d: [14, 13.6, 12.1, 8.4, 4.2, 1.8, 0.7, 0.4, 0.3, 0.3], label: '0.3%', marker: 2, markerLabel: 'failover' } },
      { t: 'step', id: 4 },
      { t: 'tool', call: "incident.note(channel: '#eng')", ms: 900, result: 'posted',
        art: { kind: 'msg', title: 'Incident note · drafted by the agent', body: 'payproc gateway degraded 02:41-03:12. Failed over to Razorpay with a circuit breaker at 03:01; error rate back to baseline in 11 minutes. No customer-visible impact. Follow-up: make failover automatic.' } },
      { t: 'done' },
    ],
    curveball: {
      label: 'Retry storm',
      steps: ['Throttle the retry backlog'],
      events: [
        { t: 'alert', title: 'Curveball', text: 'Queued retries from the outage are replaying all at once. 4× normal load is hitting the fallback provider.' },
        { t: 'step', id: 'c0' },
        { t: 'think', text: 'Draining the backlog at full rate would take the fallback down too. Cap the replay rate and let it drain over twenty minutes.' },
        { t: 'tool', call: "queue.throttle(rate: '25%')", ms: 1000, result: 'backlog draining · fallback healthy' },
      ],
    },
    outcome: {
      headline: 'Recovered in 11 minutes. Customers never noticed.',
      detail: 'Blast radius measured, the failing vendor traced and confirmed, traffic failed over behind a circuit breaker, recovery verified, and the incident note written, at 3 a.m., without waking anyone else.',
      stats: [['11 min', 'to recovery'], ['0', 'customer impact'], ['1', 'note drafted']],
    },
  },
];
