/* ════════════════════════════════════════════════════════════════════════
   AGENT CONSOLE: mission scripts. Each mission is a deterministic replay:
   a plan, a stream of events (think / step / tool / alert), one optional
   visitor-triggered curveball the agent adapts to, and an outcome.
   Event `step` ids reference plan indices; curveball steps use c0, c1…
   ════════════════════════════════════════════════════════════════════════ */

export const MISSIONS = [
  {
    id: 'a2a',
    icon: '🖨️',
    featured: true,
    badge: 'Featured · watch two AIs negotiate',
    domain: 'Procurement · Agent-to-Agent',
    short: 'A2A Commerce',
    story: "Your printer is almost out of paper. Your AI buys more from the seller's AI.",
    goal: 'The office printer is at 4% paper and the store room is empty. Handle it before Monday.',
    plan: [
      'Check the printer and inventory',
      'Find paper seller agents',
      'Compare quotes and reviews',
      'Negotiate with the seller AI',
      'Order and schedule delivery',
    ],
    events: [
      { t: 'think', text: 'The printer raised a low-paper alert. Before spending money, confirm there is really nothing left on the shelf.' },
      { t: 'step', id: 0 },
      { t: 'tool', call: "printer.status(id: 'HP-M428')", ms: 1000, result: '4% paper · about 120 sheets left' },
      { t: 'tool', call: "inventory.check(item: 'A4 80gsm')", ms: 1000, result: '0 reams in the store room · last restock 34 days ago' },
      { t: 'think', text: 'This office burns about 9 reams a month. Buying one month at a time is lazy; asking for a quarter opens bulk pricing.' },
      { t: 'step', id: 1 },
      { t: 'tool', call: "registry.discover(item: 'A4 80gsm', protocol: 'a2a/1.1')", ms: 1200, result: '3 seller AIs answering',
        art: { kind: 'kv', rows: [['PaperMill Pro', 'seller AI v4 · verified'], ['OfficeKart', 'QuoteBot · verified'], ['Sheetal Traders', 'agent v2 · verified']] } },
      { t: 'step', id: 2 },
      { t: 'tool', call: "a2a.rfq(qty: '30 reams', deliver_by: 'Mon 09:00')", ms: 1400, result: '3 machine quotes in 1.6 s',
        art: { kind: 'bars', rows: [
          { l: 'Sheetal', v: 243, txt: '₹243/ream' },
          { l: 'PaperMill', v: 247, txt: '₹247/ream' },
          { l: 'OfficeKart', v: 252, txt: '₹252/ream' },
        ] } },
      { t: 'tool', call: 'reviews.check(sellers: 3)', ms: 1100, result: 'Sheetal: 12% late deliveries · others clean' },
      { t: 'think', text: 'Sheetal is cheapest but late on one order in eight. A jammed office on Monday costs more than the ₹120 saved. Negotiating with PaperMill instead.' },
      { t: 'step', id: 3 },
      { t: 'tool', call: "a2a.negotiate(to: 'PaperMill', ask: '₹240 · free Mon delivery')", ms: 1400, result: 'their seller AI counters with a usage-based plan',
        art: { kind: 'msg', title: 'PaperMill Pro · their seller AI replies', body: 'Your office prints about 9 reams a month and trends 15% higher in reporting season. Offer: ₹239 per ream on a quarterly plan, free Monday delivery, cancel anytime. This fits the ₹8,000 quarterly budget your agent shared.' } },
      { t: 'think', text: 'Their AI predicted our usage almost exactly and beat my target by a rupee. Check the exit terms, then accept.' },
      { t: 'tool', call: "contract.verify(terms: 'cancel anytime · one-quarter price lock')", ms: 1000, result: 'clean · no lock-in' },
      { t: 'step', id: 4 },
      { t: 'tool', call: "order.place(qty: 30, delivery: 'Mon 09:00') · budget.log()", ms: 1200, result: 'PO-1247 · ₹7,170 · under budget',
        art: { kind: 'msg', title: 'Note to the office manager · written by the agent', body: 'Paper was about to run out. I compared three sellers, skipped the cheapest for reliability, and negotiated ₹239 per ream on a flexible quarterly plan (₹390 saved vs list). Delivery Monday 9 am, before anyone notices.' } },
      { t: 'done' },
    ],
    curveball: {
      label: 'Seller pushes a lock-in',
      steps: ['Refuse the lock-in, hold the terms'],
      events: [
        { t: 'alert', title: 'Curveball', text: 'The seller AI sweetens the deal: ₹231 per ream, but only on a 12-month contract with auto-renew.' },
        { t: 'step', id: 'c0' },
        { t: 'think', text: 'Cheaper per ream, but a year of lock-in while paper prices are falling is a bad trade. The mandate says flexibility beats 3%. Decline and hold.' },
        { t: 'tool', call: "a2a.negotiate(decline: '12-month lock-in', hold: 'quarterly at ₹239')", ms: 1200, result: 'seller AI accepts · quarterly plan stands' },
      ],
    },
    outcome: {
      headline: 'Paper ordered before anyone noticed it was low.',
      detail: "A printer alert became a checked inventory, three machine quotes, a reviews screen, a negotiation between two AIs and a budget-logged order, with the manager's note already sent. Every step auditable.",
      stats: [['₹390', 'saved vs list price'], ['2', 'AIs negotiating'], ['0', 'humans interrupted']],
    },
  },

  {
    id: 'retail',
    icon: '🛒',
    story: 'A store bleeds sales after an update. The agent finds the one-line bug.',
    domain: 'Retail · Analytics',
    short: 'Retail',
    goal: 'Checkout conversion dropped this week. Find out why.',
    plan: [
      'Pull the conversion funnel',
      'Segment the drop',
      'Correlate with releases',
      'Verify the root cause',
      'Draft the fix and report',
    ],
    events: [
      { t: 'think', text: 'A conversion drop is a funnel problem. First question: when did it start, and which step is bleeding?' },
      { t: 'step', id: 0 },
      { t: 'tool', call: "analytics.funnel(range: '14d')", ms: 1200, result: 'drop begins day 9 · 3.4% → 2.8%',
        art: { kind: 'spark', d: [3.4, 3.5, 3.3, 3.4, 3.6, 3.4, 3.5, 3.3, 3.4, 2.9, 2.8, 2.9, 2.8, 2.8], label: '2.8%', marker: 8, markerLabel: 'day 9' } },
      { t: 'think', text: 'A sharp knee, not a slow drift. Something changed on day 9.' },
      { t: 'step', id: 1 },
      { t: 'tool', call: "analytics.segment(step: 'payment', by: 'device')", ms: 1300, result: 'the drop is mobile-only',
        art: { kind: 'bars', rows: [
          { l: 'Desktop', v: 1.9, txt: '-1.9%' },
          { l: 'Tablet', v: 3.2, txt: '-3.2%' },
          { l: 'Mobile', v: 18, txt: '-18%', hot: true },
        ] } },
      { t: 'think', text: 'Mobile only, desktop flat. That rules out pricing, stock and payment outages.' },
      { t: 'step', id: 2 },
      { t: 'tool', call: "deploys.list(window: 'day 8-10')", ms: 1000, result: 'one release touches checkout',
        art: { kind: 'kv', rows: [
          ['v2.31 · day 9', 'checkout-ui', true],
          ['changeset', 'new address autocomplete'],
          ['v2.30 · day 8', 'email templates'],
        ] } },
      { t: 'step', id: 3 },
      { t: 'tool', call: "replay.sample(filter: 'mobile · abandoned at payment', n: 34)", ms: 1600, result: '34 sessions reviewed' },
      { t: 'alert', title: 'Root cause', text: 'The new autocomplete dropdown overlaps the Pay button on viewports under 380 px. Users tap, nothing happens, they leave.' },
      { t: 'step', id: 4 },
      { t: 'tool', call: "code.patch('checkout-ui/address.css')", ms: 1100, result: 'fix drafted · PR opened',
        art: { kind: 'diff', lines: ['  .autocomplete {', '-   z-index: 40;', '+   z-index: 10;', '+   max-height: 42vh;', '  }'] } },
      { t: 'tool', call: "report.draft(to: 'growth-team')", ms: 900, result: 'summary sent',
        art: { kind: 'msg', title: 'Report · drafted by the agent', body: 'Conversion drop isolated to mobile checkout: the v2.31 autocomplete overlays the Pay button under 380 px. One-line fix in review; est. recovery ≈ ₹4.2L/week.' } },
      { t: 'done' },
    ],
    curveball: {
      label: 'Traffic spike',
      steps: ['Hand the spike to on-call'],
      events: [
        { t: 'alert', title: 'Curveball', text: 'Marketing just launched a flash sale. Traffic is 6× normal, p95 latency 4.1 s and climbing.' },
        { t: 'step', id: 'c0' },
        { t: 'think', text: 'Tempting to chase, but the drop started on day 9 and this spike started minutes ago. Two different problems. Handing latency to on-call, staying on mission.' },
        { t: 'tool', call: "oncall.page(team: 'platform', severity: 'high')", ms: 900, result: 'acknowledged · autoscaling engaged' },
      ],
    },
    outcome: {
      headline: 'Root cause: a one-line CSS bug.',
      detail: 'Isolated to mobile in four steps, verified with session replays, fix PR opened and the report drafted, before anyone had to dig.',
      stats: [['6', 'tool calls'], ['1', 'root cause'], ['₹4.2L/wk', 'est. recovery']],
    },
  },

  {
    id: 'logistics',
    icon: '🚚',
    story: 'Fragile cargo, a hard deadline, a tight budget. The agent books it right.',
    domain: 'Logistics · Operations',
    short: 'Logistics',
    goal: '480 kg of fragile machine parts, Mumbai → Delhi by Friday. Book the cheapest safe option.',
    plan: [
      'Compute chargeable weight',
      'Quote every mode',
      'Apply the constraints',
      'Book and schedule pickup',
      'Confirm to the customer',
    ],
    events: [
      { t: 'think', text: 'Freight is priced on chargeable weight, not actual. Dimensions first.' },
      { t: 'step', id: 0 },
      { t: 'tool', call: 'rates.chargeable(4 crates · 120×80×95 cm, 480 kg)', ms: 1000, result: 'volumetric beats actual',
        art: { kind: 'kv', rows: [['actual', '480 kg'], ['volumetric', '608 kg', true], ['chargeable', '608 kg', true]] } },
      { t: 'step', id: 1 },
      { t: 'tool', call: "quotes.fetch(modes: ['air', 'rail', 'FTL', 'LTL'])", ms: 1500, result: '4 quotes returned',
        art: { kind: 'bars', rows: [
          { l: 'Air', v: 58, txt: '₹58k · 1d', hot: true },
          { l: 'FTL', v: 22, txt: '₹22k · 2d' },
          { l: 'Rail', v: 19, txt: '₹19k · 4d' },
          { l: 'LTL', v: 15, txt: '₹15k · 5d' },
        ] } },
      { t: 'think', text: 'Rail and LTL miss Friday. Air makes it at 2.6× the cost. FTL lands Thursday at ₹22k. That is the answer, if fragile handling checks out.' },
      { t: 'step', id: 2 },
      { t: 'tool', call: "carriers.check(mode: 'FTL', cargo: 'fragile')", ms: 1100, result: 'carrier B qualifies',
        art: { kind: 'kv', rows: [['carrier B', 'air-ride suspension'], ['handling', 'strap kit included'], ['rating', '4.8 / 5']] } },
      { t: 'step', id: 3 },
      { t: 'tool', call: "booking.create(carrier: 'B', pickup: 'tomorrow 09:00')", ms: 1300, result: 'AWB #MH-2841 · pickup confirmed' },
      { t: 'step', id: 4 },
      { t: 'tool', call: "notify.customer(channel: 'email')", ms: 900, result: 'confirmation sent',
        art: { kind: 'msg', title: 'Customer email · drafted by the agent', body: 'Your shipment is booked: full-truck with air-ride suspension, pickup tomorrow 09:00, arriving Thursday. ₹22,400, 61% below air freight.' } },
      { t: 'done' },
    ],
    curveball: {
      label: 'Carrier cancels',
      steps: ['Rebook with the backup carrier'],
      events: [
        { t: 'alert', title: 'Curveball', text: 'Carrier B cancelled the 09:00 pickup. Truck breakdown.' },
        { t: 'step', id: 'c0' },
        { t: 'think', text: 'This is why you quote wide. Carrier C was ₹1.3k more with the same air-ride spec. Rebooking before the slot closes.' },
        { t: 'tool', call: "booking.rebook(carrier: 'C')", ms: 1200, result: 'AWB #MH-2857 · pickup 10:30 · ETA still Thursday' },
      ],
    },
    outcome: {
      headline: 'Booked: Thursday delivery at 39% of air freight.',
      detail: 'Chargeable weight computed, four modes quoted, constraints applied, carrier vetted for fragile cargo, booking and customer email done end to end.',
      stats: [['₹35.6k', 'saved vs air'], ['Thu', 'on-time ETA'], ['4.8★', 'carrier rating']],
    },
  },

  {
    id: 'energy',
    icon: '⚡',
    story: 'Five EVs, one small fuse. The agent charges them all overnight for less.',
    domain: 'Energy · EV Charging',
    short: 'Energy',
    goal: 'Five EVs plugged in tonight, one 14 kW fuse. Everything charged by morning at the lowest cost.',
    plan: [
      'Read the site',
      'Forecast price and load',
      'Solve the schedule',
      'Hold the battery for the peak',
      'Monitor overnight',
    ],
    events: [
      { t: 'think', text: 'Five cars at full power is 35 kW into a 14 kW fuse. This is a scheduling problem, not a power problem.' },
      { t: 'step', id: 0 },
      { t: 'tool', call: 'site.read()', ms: 1000, result: 'site state loaded',
        art: { kind: 'kv', rows: [['solar', '0 kW · night'], ['battery', '11.2 / 16 kWh'], ['building load', '3.8 kW'], ['fuse', '14 kW', true]] } },
      { t: 'step', id: 1 },
      { t: 'tool', call: "forecast.price(horizon: '12h')", ms: 1200, result: 'evening peak ₹12.4 at 19:00',
        art: { kind: 'spark', d: [8.2, 9.6, 11.8, 12.4, 11.9, 9.4, 6.1, 4.3, 3.8, 3.6, 3.9, 4.4], label: '₹/kWh', marker: 3, markerLabel: '19:00 peak', color: '#f5b942' } },
      { t: 'think', text: 'Two cars must leave by 07:00; the other three have slack. They charge after midnight at a third of the price.' },
      { t: 'step', id: 2 },
      { t: 'tool', call: 'schedule.solve(evs: 5, fuse: 14 kW)', ms: 1500, result: 'peak site draw 12.7 kW · 1.3 kW margin',
        art: { kind: 'bars', rows: [
          { l: 'EV-1', v: 7, txt: '7 kW · now' },
          { l: 'EV-2', v: 3.5, txt: '3.5 kW · now' },
          { l: 'EV-3', v: 11, txt: '11 kW · 00:30' },
          { l: 'EV-4', v: 11, txt: '11 kW · 02:00' },
          { l: 'EV-5', v: 7, txt: '7 kW · 04:00' },
        ] } },
      { t: 'step', id: 3 },
      { t: 'tool', call: "battery.dispatch(reserve: '19:00-21:00', kW: 4)", ms: 1000, result: 'battery carries the building through the peak' },
      { t: 'step', id: 4 },
      { t: 'tool', call: "watchdog.arm(rules: ['fuse', 'deadlines'])", ms: 900, result: 'monitoring · re-solves on any change' },
      { t: 'done' },
    ],
    curveball: {
      label: 'A sixth EV arrives',
      steps: ['Re-solve for the sixth car'],
      events: [
        { t: 'alert', title: 'Curveball', text: 'A sixth EV just plugged in at 21:40. It needs 22 kWh by 08:00.' },
        { t: 'step', id: 'c0' },
        { t: 'think', text: 'The solver re-runs in milliseconds. EV-4 has deadline slack. Shifting it 40 minutes frees a slot for the newcomer.' },
        { t: 'tool', call: 'schedule.resolve(evs: 6)', ms: 1100, result: 'still under the fuse · all deadlines met' },
      ],
    },
    outcome: {
      headline: 'All cars ready by 07:00. Fuse never touched.',
      detail: 'Deadline-aware charging shifted to cheap hours, the battery covered the price peak, and a watchdog re-solves the moment anything changes. This one is our day job at RiDERgy.',
      stats: [['-34%', 'energy cost'], ['0', 'fuse breaches'], ['5/5', 'cars ready']],
    },
  },

  {
    id: 'incident',
    icon: '🚨',
    story: 'A 3 a.m. outage. The agent fixes it before customers wake up.',
    domain: 'SaaS · Incident Response',
    short: 'Incident',
    goal: '3 a.m. page: API error rate climbing. Triage it before customers notice.',
    plan: [
      'Measure the blast radius',
      'Trace the failure',
      'Mitigate',
      'Verify recovery',
      'Write the incident note',
    ],
    events: [
      { t: 'step', id: 0 },
      { t: 'tool', call: "metrics.query(error_rate, by: 'endpoint')", ms: 1100, result: 'isolated to payment paths',
        art: { kind: 'bars', rows: [
          { l: '/payments', v: 14, txt: '14% err', hot: true },
          { l: '/checkout', v: 6, txt: '6% err', hot: true },
          { l: '/catalog', v: 0.2, txt: '0.2%' },
          { l: '/auth', v: 0.1, txt: '0.1%' },
        ] } },
      { t: 'step', id: 1 },
      { t: 'tool', call: "traces.sample(endpoint: '/payments', n: 50)", ms: 1300, result: '92% are upstream timeouts',
        art: { kind: 'kv', rows: [['p50', '180 ms'], ['p95', '30 000 ms · timeout', true], ['upstream', 'payproc-gw', true]] } },
      { t: 'think', text: 'Every slow trace dies at the same upstream. That smells like their outage, not our bug. Check their status before touching code.' },
      { t: 'tool', call: "status.check(vendor: 'payproc')", ms: 900, result: "vendor incident confirmed · 'degraded performance' since 02:41" },
      { t: 'step', id: 2 },
      { t: 'tool', call: "config.apply(fallback: 'razorpay', circuit_breaker: on)", ms: 1200, result: 'traffic failing over',
        art: { kind: 'diff', lines: ['  payments:', '-   provider: payproc', '+   provider: razorpay', '+   breaker: open @ 5xx > 2%'] } },
      { t: 'step', id: 3 },
      { t: 'tool', call: "metrics.watch(error_rate, '5m')", ms: 1600, result: 'recovered · 0.3% baseline',
        art: { kind: 'spark', d: [14, 13.6, 12.1, 8.4, 4.2, 1.8, 0.7, 0.4, 0.3, 0.3], label: '0.3%', marker: 2, markerLabel: 'failover' } },
      { t: 'step', id: 4 },
      { t: 'tool', call: "incident.note(channel: '#eng')", ms: 900, result: 'posted',
        art: { kind: 'msg', title: 'Incident note · drafted by the agent', body: 'payproc gateway degraded 02:41-03:12. Failed over to Razorpay with a circuit breaker at 03:01; error rate back to baseline in 11 minutes. No customer-visible impact. Follow-up: make failover automatic.' } },
      { t: 'done' },
    ],
    curveball: {
      label: 'Retry storm',
      steps: ['Throttle the retry backlog'],
      events: [
        { t: 'alert', title: 'Curveball', text: 'Queued retries from the outage are replaying all at once. 4× normal load is hitting the fallback provider.' },
        { t: 'step', id: 'c0' },
        { t: 'think', text: 'Draining the backlog at full rate would take the fallback down too. Cap the replay rate and let it drain over twenty minutes.' },
        { t: 'tool', call: "queue.throttle(rate: '25%')", ms: 1000, result: 'backlog draining · fallback healthy' },
      ],
    },
    outcome: {
      headline: 'Recovered in 11 minutes. Customers never noticed.',
      detail: 'Blast radius measured, the failing vendor traced and confirmed, traffic failed over behind a circuit breaker, recovery verified, and the incident note written, at 3 a.m., without waking anyone else.',
      stats: [['11 min', 'to recovery'], ['0', 'customer impact'], ['1', 'note drafted']],
    },
  },

  {
    id: 'seller',
    icon: '📈',
    story: "Rain is coming. The seller's AI spots it first and sells the surge.",
    domain: 'D2C · Autonomous Sales',
    short: 'Seller AI',
    goal: 'Monsoon is coming. Find the demand, pick the audience, price it and launch before competitors move.',
    plan: [
      'Scan demand signals',
      'Pick product and audience',
      'Set price and margin',
      'Launch the campaign',
      'Position inventory',
    ],
    events: [
      { t: 'step', id: 0 },
      { t: 'tool', call: "market.scan(signals: ['search', 'social', 'weather'])", ms: 1300, result: 'demand spike forming',
        art: { kind: 'spark', d: [12, 14, 13, 16, 19, 24, 31, 42, 58, 71], label: 'intent index', marker: 6, markerLabel: 'today' } },
      { t: 'think', text: 'Search interest for roof waterproofing is climbing in three cities, 11 days earlier than last season. The market has not repriced yet.' },
      { t: 'step', id: 1 },
      { t: 'tool', call: "audience.segment(intent: 'roof waterproofing')", ms: 1200, result: '2 segments · 34k households',
        art: { kind: 'bars', rows: [
          { l: 'Homeowners', v: 22, txt: '22k · high intent' },
          { l: 'Societies', v: 12, txt: '12k · bulk orders' },
        ] } },
      { t: 'step', id: 2 },
      { t: 'tool', call: "price.optimize(margin_floor: '22%')", ms: 1200, result: 'price ladder set',
        art: { kind: 'kv', rows: [['launch price', '₹649'], ['late-season', '₹749'], ['margin at launch', '26%']] } },
      { t: 'step', id: 3 },
      { t: 'tool', call: "campaign.launch(channels: ['WhatsApp', 'Instagram'], budget: 'auto')", ms: 1300, result: 'live · first 200 sends out' },
      { t: 'alert', title: 'Early signal', text: 'WhatsApp click-through at 9.8%, three times the benchmark. Scaling spend 2x, still inside the guardrails.' },
      { t: 'step', id: 4 },
      { t: 'tool', call: 'inventory.route(dark_stores: 3)', ms: 1100, result: 'stock positioned ahead of the demand peak',
        art: { kind: 'msg', title: 'Daily brief · written by the agent', body: 'Campaign live 6 hours: 214 orders, CAC ₹31 against a ₹95 target, margin 26%. Stock moved to 3 dark stores before the rain hits. Recommend adding Pune tomorrow.' } },
      { t: 'done' },
    ],
    curveball: {
      label: 'Competitor undercuts',
      steps: ['Counter the price war with a bundle'],
      events: [
        { t: 'alert', title: 'Curveball', text: 'A rival just listed the same product at ₹599, under our launch price.' },
        { t: 'step', id: 'c0' },
        { t: 'think', text: 'Matching ₹599 breaks the 22% margin floor and starts a race to the bottom. Better move: raise perceived value instead. Bundle the application-service warranty at ₹679.' },
        { t: 'tool', call: "offer.bundle(add: 'service warranty', price: '₹679')", ms: 1200, result: 'conversion holds · margin at 24%' },
      ],
    },
    outcome: {
      headline: 'Sold the surge before the market noticed it.',
      detail: 'Demand spotted 11 days early from public signals, the audience segmented, the price laddered above the margin floor, the campaign launched and scaled on live results, and inventory moved ahead of the peak. One agent, end to end.',
      stats: [['11 days', 'ahead of market'], ['₹31', 'CAC vs ₹95 target'], ['24%', 'margin held']],
    },
  },
];
